# Generated by Django 5.2.5 on 2025-10-23 08:39

import applications.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=2500.0, help_text='Amount paid for application', max_digits=10),
        ),
        migrations.AddField(
            model_name='applicant',
            name='payment_email',
            field=models.EmailField(blank=True, help_text='Email used for payment verification', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Paystack payment reference', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='payment_verified',
            field=models.BooleanField(default=False, help_text='Whether payment was verified automatically'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='receipt',
            field=models.FileField(blank=True, help_text='Upload payment receipt (PDF, JPG, PNG only) - Optional for online payments', null=True, upload_to=applications.models.receipt_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
